login: &login
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: 5
  username: postgres
  password: password

development:
  <<: *login
  database: rqtech_development

test:
  <<: *login
  database: rqtech_test
